### ISSUE TITLE
Integration is using outdated Swrve SDK version. 

### ISSUE THREAD

**Issue by dpiletski** [swrve-services/analytics-ios-integration-swrve#1]
Integration is using Swrve version 4.x, where the latest is 5.2.2. 
Currently it is blocking project from compiling on Xcode 9.3. This issue is resolved in iOS Swrve SDK v5.2.2.

**Comment by davidbreenwex** [comment]
Hi Danil, 

I'll work on getting this upgraded for you as soon as possible and let you know once it has been completed.

**Comment by dpiletski** [comment]
Thank you @davidbreenwex
